[package]
name = "rule-validator"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
validator = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
regex = { workspace = true }
